"""A frozen two-run sequence for the shadow-fill identity tests (K-06).

The pre-change output of this exact sequence is stored in
tests/fixtures/pm_golden_prechange_shadow.json. It was generated by running this module's
`replay()` against the engine at commit d02bcee (the last commit before shadow fills), with
`python3 tests/shadow_sequence.py --write`. The tests then prove that with the shadow model
switched OFF the engine still writes those bytes, and with it ON the only difference is the
new keys.

Everything here is pinned: the clock, the quotes, the scan time. Nothing depends on the
wall clock, so the golden does not age.
"""
import copy
import datetime as dt
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
ENGINE = ROOT / "engine"
FIX = pathlib.Path(__file__).resolve().parent / "fixtures"
GOLDEN = FIX / "pm_golden_prechange_shadow.json"

T1 = "2026-09-10T14:45:00Z"      # 10:45 ET — opening-range
T2 = "2026-09-10T17:15:00Z"      # 13:15 ET — midday

# Quotes for run 2: HOOD gaps through its 93.85 stop, NVDA prints through its 257.05
# target, SCHW comes back to the limit so the resting entry fills.
RUN2_QUOTES = {
    "HOOD": ("90.000000", "89.950000", "90.050000"),
    "NVDA": ("260.000000", "259.950000", "260.050000"),
    "SCHW": ("92.300000", "92.250000", "92.350000"),
}


def _quote_row(sym, last, bid, ask, ts):
    return {"quote": {"symbol": sym, "last_trade_price": last, "venue_last_trade_time": ts,
                      "last_non_reg_trade_price": None, "venue_last_non_reg_trade_time": None,
                      "bid_price": bid, "venue_bid_time": ts, "ask_price": ask,
                      "venue_ask_time": ts, "has_traded": True, "state": "active"}}


def stage(tmp_path):
    for f in ENGINE.glob("*.json"):
        shutil.copy(f, tmp_path / f.name)
    for name, dest in (("book_swing.json", "paper_book.json"),
                       ("book_pullback.json", "paper_book_pullback.json"),
                       ("book_momentum.json", "paper_book_momentum.json")):
        shutil.copy(FIX / name, tmp_path / dest)


def inputs(ts_iso, run2=False):
    """(scan, quotes payload) for a run stamped at ts_iso."""
    scan = json.loads((FIX / "scan.json").read_text(encoding="utf-8"))
    scan["meta"]["scan_date"] = "2026-09-10"
    scan["meta"]["time"] = "10:15"
    payload = json.loads((FIX / "quotes.json").read_text(encoding="utf-8"))
    for row in payload["data"]["results"]:
        q = row["quote"]
        q["venue_last_trade_time"] = q["venue_bid_time"] = q["venue_ask_time"] = ts_iso
        if run2 and q["symbol"] in RUN2_QUOTES:
            q["last_trade_price"], q["bid_price"], q["ask_price"] = RUN2_QUOTES[q["symbol"]]
    if run2:
        payload["data"]["results"].append(_quote_row("SCHW", *RUN2_QUOTES["SCHW"], ts_iso))
    else:
        payload["data"]["results"].append(
            _quote_row("SCHW", "92.400000", "92.350000", "92.450000", ts_iso))
    return scan, payload


def replay(pm, run_dir, pm_rules_override=None):
    """Two runs on the swing book. Returns {"book", "journal", "state"} of the final run."""
    stage(run_dir)
    pm.DESK.update({"name": "swing", "filter": {}, "suffix": ""})
    pm.PEERS.update({"books": {}, "loaded": [], "missing": []})
    for k, v in (pm_rules_override or {}).items():
        pm.PM_RULES[k] = copy.deepcopy(v)
    pm.load_peers("desks.json", "swing", "paper_book.json")
    book = json.loads((run_dir / "paper_book.json").read_text(encoding="utf-8"))
    entries = []
    for ts, run2, slot in ((T1, False, "opening-range"), (T2, True, "midday")):
        scan, payload = inputs(ts, run2)
        prices, _ = pm.quotes_to_prices(payload, pm._now(ts))
        book, jrn, state = pm.run(book, scan, prices, slot, ts, "paper")
        entries.append(jrn)
        book = json.loads(json.dumps(book))       # round-trip, as the file write would
    return {"book": book, "journal": {"entries": entries}, "state": state}


if __name__ == "__main__":
    import tempfile, importlib
    with tempfile.TemporaryDirectory() as d:
        import os
        os.environ["SCAN_DIR"] = d
        sys.path.insert(0, str(ENGINE))
        import pm
        importlib.reload(pm)
        out = replay(pm, pathlib.Path(d))
    if "--write" in sys.argv:
        GOLDEN.write_text(json.dumps(out, indent=1, sort_keys=True), encoding="utf-8")
        print(f"wrote {GOLDEN}")
    else:
        print(json.dumps({"decisions": [(d["action"], d["symbol"], d["price"])
                                        for e in out["journal"]["entries"]
                                        for d in e["decisions"]]}, indent=1))
