"""A frozen three-run sequence for the stop-policy identity test (K-07).

The pre-change output of this exact sequence is stored in
tests/fixtures/pm_golden_prechange_stops.json. It was generated by running `replay()`
against the engine at commit 3a72721 — the last commit before engine/stops.py existed —
with `python3 tests/stops_sequence.py --write`, BEFORE pm.py was modified. The test then
proves that the default `fixed_atr` policy (every existing desk) still writes those bytes,
plus only the new bookkeeping keys.

The sequence reuses shadow_sequence's pinned inputs and adds a third run on the NEXT
session so the session roll, a breakeven stop after a scale-out and a filled entry are all
carried across a day boundary. Nothing depends on the wall clock.
"""
import json
import pathlib
import sys

import shadow_sequence as ss

FIX = pathlib.Path(__file__).resolve().parent / "fixtures"
GOLDEN = FIX / "pm_golden_prechange_stops.json"

T3 = "2026-09-11T14:45:00Z"      # next session, 10:45 ET — opening-range


def replay(pm, run_dir, pm_rules_override=None):
    """Three runs on the swing book under the engine's default rules.
    Returns {"book", "journal", "state"} of the final run."""
    ss.stage(run_dir)
    pm.DESK.update({"name": "swing", "filter": {}, "suffix": ""})
    pm.PEERS.update({"books": {}, "loaded": [], "missing": []})
    for k, v in (pm_rules_override or {}).items():
        pm.PM_RULES[k] = json.loads(json.dumps(v))
    pm.load_peers("desks.json", "swing", "paper_book.json")
    book = json.loads((run_dir / "paper_book.json").read_text(encoding="utf-8"))
    entries = []
    for ts, run2, slot in ((ss.T1, False, "opening-range"), (ss.T2, True, "midday"),
                           (T3, True, "opening-range")):
        scan, payload = ss.inputs(ts, run2)
        if ts == T3:
            scan["meta"]["scan_date"] = "2026-09-11"
        prices, _ = pm.quotes_to_prices(payload, pm._now(ts))
        book, jrn, state = pm.run(book, scan, prices, slot, ts, "paper")
        entries.append(jrn)
        book = json.loads(json.dumps(book))       # round-trip, as the file write would
    return {"book": book, "journal": {"entries": entries}, "state": state}


if __name__ == "__main__":
    import tempfile, importlib, os
    with tempfile.TemporaryDirectory() as d:
        os.environ["SCAN_DIR"] = d
        sys.path.insert(0, str(ss.ENGINE))
        import pm
        importlib.reload(pm)
        out = replay(pm, pathlib.Path(d))
    if "--write" in sys.argv:
        GOLDEN.write_text(json.dumps(out, indent=1, sort_keys=True), encoding="utf-8")
        print(f"wrote {GOLDEN}")
    else:
        print(json.dumps({"decisions": [(d["action"], d["symbol"], d["price"])
                                        for e in out["journal"]["entries"]
                                        for d in e["decisions"]]}, indent=1))
